import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for FluentHire — AI-powered English interview practice for developers.",
  alternates: { canonical: "/terms" },
};

const EFFECTIVE_DATE = "April 8, 2026";

const SECTIONS = [
  "Acceptance of Terms",
  "Description of Service",
  "Account Registration",
  "Subscription Plans & Payments",
  "Credits & Usage",
  "Refund Policy",
  "User Content",
  "AI-Generated Content",
  "Communications",
  "Acceptable Use",
  "Intellectual Property",
  "Termination",
  "Disclaimers",
  "Limitation of Liability",
  "Governing Law",
  "Changes to Terms",
  "Contact",
];

function SectionHeading({
  id,
  index,
  children,
}: {
  id: string;
  index: number;
  children: React.ReactNode;
}) {
  return (
    <h2 id={id} className="mt-10 mb-4 text-xl font-semibold scroll-mt-24">
      {index}. {children}
    </h2>
  );
}

export default function TermsPage() {
  return (
    <article>
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Effective date: {EFFECTIVE_DATE}
      </p>

      {/* Table of Contents */}
      <nav className="mt-8 rounded-lg border border-border p-5">
        <p className="mb-3 text-sm font-semibold">Table of Contents</p>
        <ol className="list-decimal space-y-1 pl-5 text-sm text-muted-foreground">
          {SECTIONS.map((s, i) => (
            <li key={s}>
              <a
                href={s === "Refund Policy" ? "#refund-policy" : `#section-${i + 1}`}
                className="transition-colors hover:text-foreground"
              >
                {s}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {/* Sections */}
      <div className="text-sm leading-relaxed text-muted-foreground">
        <SectionHeading id="section-1" index={1}>
          Acceptance of Terms
        </SectionHeading>
        <p>
          By creating an account or using FluentHire (&ldquo;the
          Service&rdquo;), you agree to be bound by these Terms of Service
          (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.
        </p>
        <p className="mt-3">
          You must be at least 13 years old to use FluentHire. If you are under
          18, you must have the consent of a parent or legal guardian.
        </p>

        <SectionHeading id="section-2" index={2}>
          Description of Service
        </SectionHeading>
        <p>
          FluentHire is an AI-powered English interview practice platform for
          software developers. The Service offers multiple practice formats
          including Q&A, Think Out Loud, Coding Interview, and Behavioral
          interviews.
        </p>
        <p className="mt-3">
          Scores, feedback, and improved responses generated by the platform are
          educational in nature and are not guarantees of real-world interview
          performance.
        </p>

        <SectionHeading id="section-3" index={3}>
          Account Registration
        </SectionHeading>
        <p>
          You must provide accurate information when creating an account. You may
          register with an email address and password or through Google OAuth.
          Each person may maintain only one account.
        </p>
        <p className="mt-3">
          You are responsible for maintaining the confidentiality of your
          credentials. Your account may be temporarily locked after repeated
          failed login attempts.
        </p>

        <SectionHeading id="section-4" index={4}>
          Subscription Plans & Payments
        </SectionHeading>
        <p>FluentHire offers the following subscription tiers:</p>
        <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>
            <strong className="text-foreground">Free</strong> — 3 Live AI
            Interview credits + unlimited Q&A and Think Out Loud practice
          </li>
          <li>
            <strong className="text-foreground">Interview Starter ($9.99/mo)</strong> — 5
            Live AI Interview credits per month
          </li>
          <li>
            <strong className="text-foreground">Interview Pro ($19.99/mo)</strong> — 14
            Live AI Interview credits per month
          </li>
          <li>
            <strong className="text-foreground">Interview Intensive ($29.99/mo)</strong> — 24
            Live AI Interview credits per month
          </li>
        </ul>
        <p className="mt-3">
          One-time credit packs are also available for purchase without a
          subscription:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>
            <strong className="text-foreground">3-Credit Pack</strong> — $8.99
          </li>
          <li>
            <strong className="text-foreground">6-Credit Pack</strong> — $14.99
          </li>
          <li>
            <strong className="text-foreground">10-Credit Pack</strong> — $22.99
          </li>
        </ul>
        <p className="mt-3">
          Payments are processed securely through Stripe. You may cancel your
          subscription at any time; access continues until the end of the current
          billing period. We will provide at least 30 days&apos; notice before
          any price changes.
        </p>

        <SectionHeading id="section-5" index={5}>
          Credits & Usage
        </SectionHeading>
        <p>
          Each Live AI Interview session costs 1 credit. Subscription credits
          reset monthly on your billing cycle date and do not roll over to the
          next period. Credits purchased through credit packs do not expire.
          Q&amp;A and Think Out Loud practice are free and unlimited for all
          users.
        </p>

        <SectionHeading id="refund-policy" index={6}>
          Refund Policy
        </SectionHeading>
        <p>
          Subscription payments are non-refundable. When you cancel your
          subscription, you retain access to paid features until the end of
          your current billing period. No partial or prorated refunds are
          issued for unused time within a billing cycle.
        </p>
        <p className="mt-3">
          Credits that have been used (consumed by a Live AI Interview session)
          are non-refundable. Unused credit pack credits remain on your account
          and do not expire.
        </p>
        <p className="mt-3">
          If you experience a technical failure during a Live AI Interview
          session that prevents you from completing or receiving results
          (such as a platform error, AI disconnection, or audio processing
          failure), we may restore the credit used for that session at our
          discretion. Contact{" "}
          <a
            href="mailto:support@fluenthire.app"
            className="text-primary hover:underline"
          >
            support@fluenthire.app
          </a>{" "}
          within 7 days of the incident to request a credit restoration.
        </p>

        <SectionHeading id="section-7" index={7}>
          User Content
        </SectionHeading>
        <p>
          You retain ownership of all content you submit, including interview
          responses, code submissions, and job descriptions (&ldquo;User
          Content&rdquo;).
        </p>
        <p className="mt-3">
          By using the Service, you grant FluentHire a limited, non-exclusive
          license to process your User Content through AI systems for the sole
          purpose of providing feedback and analysis. Anonymized, aggregated data
          may be used to improve the Service.
        </p>

        <SectionHeading id="section-8" index={8}>
          AI-Generated Content
        </SectionHeading>
        <p>
          The Service uses third-party AI models (including Anthropic&apos;s
          Claude and OpenAI) to generate feedback, scores, and improved
          responses. This content is provided for educational purposes only and
          does not constitute professional career advice. We do not guarantee the
          accuracy, completeness, or reliability of AI-generated content.
        </p>

        <SectionHeading id="section-9" index={9}>
          Communications
        </SectionHeading>
        <p>
          By creating an account, you agree to receive transactional emails
          related to your account, including welcome emails, subscription
          confirmations, and password reset emails.
        </p>
        <p className="mt-3">
          We may also send engagement emails such as credit reminders and
          re-engagement messages. These are sent infrequently and are designed
          to help you get the most from the platform. You may contact{" "}
          <a
            href="mailto:support@fluenthire.app"
            className="text-primary hover:underline"
          >
            support@fluenthire.app
          </a>{" "}
          to opt out of non-essential emails at any time.
        </p>

        <SectionHeading id="section-10" index={10}>
          Acceptable Use
        </SectionHeading>
        <p>You agree not to:</p>
        <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>
            Submit malicious, harmful, or illegal content through the Service
          </li>
          <li>
            Attempt to reverse-engineer, extract, or reconstruct AI prompts or
            system instructions
          </li>
          <li>Share your account credentials with others</li>
          <li>
            Circumvent rate limits, usage restrictions, or security measures
          </li>
          <li>
            Use the Service to infringe on the intellectual property rights of
            others
          </li>
          <li>
            Automate access to the Service without prior written permission
          </li>
        </ul>

        <SectionHeading id="section-11" index={11}>
          Intellectual Property
        </SectionHeading>
        <p>
          FluentHire and its licensors own all rights in the platform, including
          the question bank, AI prompts, user interface, and underlying
          technology. You may not reproduce, distribute, or create derivative
          works from any part of the Service without prior written permission.
        </p>

        <SectionHeading id="section-12" index={12}>
          Termination
        </SectionHeading>
        <p>
          We may suspend or terminate your account if you violate these Terms.
          You may delete your account at any time. Upon account deletion, your
          data will be removed in accordance with our{" "}
          <Link href="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>
          .
        </p>

        <SectionHeading id="section-13" index={13}>
          Disclaimers
        </SectionHeading>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind, whether express or
          implied. FluentHire is not a substitute for professional interview
          coaching, career counseling, or employment services.
        </p>

        <SectionHeading id="section-14" index={14}>
          Limitation of Liability
        </SectionHeading>
        <p>
          To the maximum extent permitted by law, FluentHire&apos;s total
          liability for any claims arising from or related to the Service is
          limited to the amount you paid to FluentHire in the 12 months
          preceding the claim.
        </p>
        <p className="mt-3">
          In no event shall FluentHire be liable for any indirect, incidental,
          special, consequential, or punitive damages, including loss of profits,
          data, or goodwill.
        </p>

        <SectionHeading id="section-15" index={15}>
          Governing Law
        </SectionHeading>
        <p>
          These Terms are governed by the laws of the State of Delaware, USA,
          without regard to its conflict of law provisions. Any disputes arising
          from these Terms shall be resolved exclusively in the courts located in
          the State of Delaware.
        </p>

        <SectionHeading id="section-16" index={16}>
          Changes to Terms
        </SectionHeading>
        <p>
          We may update these Terms from time to time. When we do, we will
          revise the effective date at the top of this page. Your continued use
          of the Service after changes are posted constitutes acceptance of the
          updated Terms.
        </p>

        <SectionHeading id="section-17" index={17}>
          Contact
        </SectionHeading>
        <p>
          If you have any questions about these Terms, please contact us at{" "}
          <a
            href="mailto:support@fluenthire.app"
            className="text-primary hover:underline"
          >
            support@fluenthire.app
          </a>
          .
        </p>
      </div>
    </article>
  );
}
