import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How FluentHire collects, uses, and protects your personal data.",
  alternates: { canonical: "/privacy" },
};

const EFFECTIVE_DATE = "April 6, 2026";

const SECTIONS = [
  "Introduction",
  "Data We Collect",
  "How We Use Your Data",
  "Third-Party Services",
  "Data Storage & Security",
  "Data Retention",
  "Your Rights",
  "Children's Privacy",
  "International Data Transfers",
  "No Tracking or Advertising",
  "Changes to This Policy",
  "Contact Us",
];

function SectionHeading({
  id,
  index,
  children,
}: {
  id: string;
  index: number;
  children: React.ReactNode;
}) {
  return (
    <h2 id={id} className="mt-10 mb-4 text-xl font-semibold scroll-mt-24">
      {index}. {children}
    </h2>
  );
}

export default function PrivacyPage() {
  return (
    <article>
      <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Effective date: {EFFECTIVE_DATE}
      </p>

      {/* Table of Contents */}
      <nav className="mt-8 rounded-lg border border-border p-5">
        <p className="mb-3 text-sm font-semibold">Table of Contents</p>
        <ol className="list-decimal space-y-1 pl-5 text-sm text-muted-foreground">
          {SECTIONS.map((s, i) => (
            <li key={s}>
              <a
                href={`#privacy-${i + 1}`}
                className="transition-colors hover:text-foreground"
              >
                {s}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {/* Sections */}
      <div className="text-sm leading-relaxed text-muted-foreground">
        <SectionHeading id="privacy-1" index={1}>
          Introduction
        </SectionHeading>
        <p>
          FluentHire (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;)
          operates an AI-powered English interview practice platform for software
          developers. This Privacy Policy explains how we collect, use, store,
          and protect your personal data when you use our Service.
        </p>
        <p className="mt-3">
          This policy includes provisions that apply under the Lei Geral de
          Prote&ccedil;&atilde;o de Dados (LGPD) for users in Brazil and the
          General Data Protection Regulation (GDPR) for users in the European
          Union, where applicable.
        </p>

        <SectionHeading id="privacy-2" index={2}>
          Data We Collect
        </SectionHeading>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Account Data
        </h3>
        <p>
          Email address, first and last name, and a hashed password. If you sign
          up via Google OAuth, we receive your Google profile information (name
          and email).
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Profile Preferences
        </h3>
        <p>
          Native language, English comfort level, communication challenges,
          experience level, target role type, and primary programming language —
          provided during onboarding to personalize your practice sessions and
          feedback.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Job Descriptions
        </h3>
        <p>
          Full text of job descriptions you upload, along with AI-extracted
          fields such as job title, technologies, and key responsibilities.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Interview & Practice Data
        </h3>
        <p>
          Transcripts, code submissions, written answers, and attempt numbers
          from your practice sessions.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          AI Analysis Data
        </h3>
        <p>
          Scores, feedback, and improved responses generated by AI models based
          on your practice sessions.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Audio Data
        </h3>
        <p>
          User audio is transcribed and then discarded — we do{" "}
          <strong className="text-foreground">not</strong> store audio
          recordings. In Coding Interview mode, audio streams directly from your
          browser to OpenAI and is not routed through our servers. Text-to-speech
          audio may be temporarily cached.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Payment Data
        </h3>
        <p>
          We store only Stripe customer and subscription identifiers. Credit card
          numbers and payment details are{" "}
          <strong className="text-foreground">never</strong> stored by
          FluentHire.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Credit Transactions
        </h3>
        <p>Transaction type, credit amount, and timestamp.</p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Security Data
        </h3>
        <p>
          Failed login attempt counts, account lockout times, and password reset
          tokens (which expire after 1 hour).
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          Browser Storage
        </h3>
        <p>
          A JSON Web Token (JWT) stored in localStorage with a 30-day expiry for
          authentication, and 4 tour completion flags. We do{" "}
          <strong className="text-foreground">not</strong> use tracking cookies.
        </p>

        <SectionHeading id="privacy-3" index={3}>
          How We Use Your Data
        </SectionHeading>
        <p>We use your data to:</p>
        <ul className="mt-3 list-disc space-y-2 pl-6">
          <li>Provide the Service and generate AI-powered feedback</li>
          <li>Process payments through Stripe</li>
          <li>Send password reset emails</li>
          <li>Improve the Service using anonymized, aggregated data</li>
          <li>Enforce rate limits and usage restrictions</li>
          <li>Protect the security and integrity of the platform</li>
        </ul>

        <SectionHeading id="privacy-4" index={4}>
          Third-Party Services
        </SectionHeading>
        <p>We share data with the following third-party services:</p>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="pb-2 pr-4 font-semibold text-foreground">
                  Service
                </th>
                <th className="pb-2 pr-4 font-semibold text-foreground">
                  Data Shared
                </th>
                <th className="pb-2 font-semibold text-foreground">Purpose</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              <tr>
                <td className="py-2 pr-4">Stripe</td>
                <td className="py-2 pr-4">Email, name, user ID</td>
                <td className="py-2">Payment processing</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Anthropic (Claude)</td>
                <td className="py-2 pr-4">
                  Questions, responses, JD text, code, transcripts (no PII)
                </td>
                <td className="py-2">AI analysis &amp; scoring</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">OpenAI Whisper</td>
                <td className="py-2 pr-4">Audio files (max 10 MB)</td>
                <td className="py-2">Speech-to-text</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">OpenAI TTS</td>
                <td className="py-2 pr-4">
                  Improved response text (max 4096 chars)
                </td>
                <td className="py-2">Text-to-speech</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">OpenAI Realtime</td>
                <td className="py-2 pr-4">
                  Live audio (client → OpenAI direct via ephemeral token)
                </td>
                <td className="py-2">Live AI interview</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Resend</td>
                <td className="py-2 pr-4">Email, first name</td>
                <td className="py-2">
                  Transactional and engagement emails (welcome,
                  subscription confirmation, password reset, credit
                  reminders, re-engagement)
                </td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Sentry</td>
                <td className="py-2 pr-4">
                  Error data, browser info, request metadata (no PII)
                </td>
                <td className="py-2">Error monitoring and performance tracking</td>
              </tr>
              <tr>
                <td className="py-2 pr-4">Google OAuth</td>
                <td className="py-2 pr-4">ID token verification</td>
                <td className="py-2">Authentication</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-4">
          We do <strong className="text-foreground">not</strong> sell your data.
          We do not share data with advertisers. We do not use any analytics or
          tracking services.
        </p>

        <SectionHeading id="privacy-5" index={5}>
          Data Storage & Security
        </SectionHeading>
        <p>
          Your data is stored in a PostgreSQL database. Passwords are securely
          hashed before storage. Authentication is handled via JSON Web Tokens
          over HTTPS.
        </p>
        <p className="mt-3">
          We implement security headers including X-Frame-Options DENY,
          X-Content-Type-Options nosniff, and a strict Referrer-Policy. Rate
          limiting is applied to authentication and AI endpoints.
        </p>

        <SectionHeading id="privacy-6" index={6}>
          Data Retention
        </SectionHeading>
        <p>
          Your data is retained while your account is active. If you delete your
          account, your personal data will be removed within 30 days. Password
          reset tokens expire after 1 hour. Anonymized, aggregated data may be
          retained indefinitely.
        </p>

        <SectionHeading id="privacy-7" index={7}>
          Your Rights
        </SectionHeading>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          All Users
        </h3>
        <p>
          You have the right to access, correct, delete, and export your
          personal data. Contact us at{" "}
          <a
            href="mailto:support@fluenthire.app"
            className="text-primary hover:underline"
          >
            support@fluenthire.app
          </a>{" "}
          to exercise these rights.
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          LGPD (Brazil)
        </h3>
        <p>
          If you are located in Brazil, you have additional rights under the
          LGPD, including: confirmation of data processing, anonymization of
          unnecessary data, information about third parties with whom your data
          is shared, revocation of consent, and the right to petition the
          Autoridade Nacional de Prote&ccedil;&atilde;o de Dados (ANPD).
        </p>

        <h3 className="mt-6 mb-2 text-base font-medium text-foreground">
          GDPR (European Union)
        </h3>
        <p>
          If applicable, EU users have additional rights including data
          portability, the right to restrict processing, the right to object to
          processing, and the right to lodge a complaint with a supervisory
          authority.
        </p>

        <SectionHeading id="privacy-8" index={8}>
          Children&apos;s Privacy
        </SectionHeading>
        <p>
          FluentHire is not intended for children under 13. Users under 18 must
          have parental consent. If we become aware that we have collected data
          from a child under 13, we will promptly delete that data.
        </p>

        <SectionHeading id="privacy-9" index={9}>
          International Data Transfers
        </SectionHeading>
        <p>
          Our third-party service providers primarily operate servers in the
          United States. By using the Service, you acknowledge that your data may
          be transferred to and processed in the United States and other
          jurisdictions. We ensure appropriate safeguards are in place as
          required by applicable law.
        </p>

        <SectionHeading id="privacy-10" index={10}>

          No Tracking or Advertising
        </SectionHeading>
        <p>
          We do not use cookies for tracking purposes. We do not use
          behavioral analytics services (such as Google Analytics, Plausible, or
          PostHog). We do not display advertisements. We use Sentry solely for
          error monitoring and performance tracking — it does not track user
          behavior or browsing activity.
        </p>

        <SectionHeading id="privacy-11" index={11}>
          Changes to This Policy
        </SectionHeading>
        <p>
          We may update this Privacy Policy from time to time. When we make
          material changes, we will update the effective date at the top of this
          page and notify you via email. Your continued use of the Service after
          changes are posted constitutes acceptance.
        </p>

        <SectionHeading id="privacy-12" index={12}>
          Contact Us
        </SectionHeading>
        <p>
          If you have any questions about this Privacy Policy or wish to exercise
          your data rights, please contact us at{" "}
          <a
            href="mailto:support@fluenthire.app"
            className="text-primary hover:underline"
          >
            support@fluenthire.app
          </a>
          .
        </p>
        <p className="mt-3">
          See also our{" "}
          <Link href="/terms" className="text-primary hover:underline">
            Terms of Service
          </Link>
          .
        </p>
      </div>
    </article>
  );
}
