package com.fluenthire.entity;

public enum AlgorithmCategory {

    ARRAYS_AND_HASH_MAPS, STRINGS, TWO_POINTERS_AND_SORTING,
    STACKS_AND_QUEUES, BINARY_SEARCH, LINKED_LISTS, TREES,
    GRAPHS_AND_MATRIX, DYNAMIC_PROGRAMMING, BACKTRACKING,
    HEAPS_AND_PRIORITY_QUEUES, TRIES, INTERVALS,
    BIT_MANIPULATION, GREEDY
}
